import { GraphQLClient } from 'graphql-request';
import type { ChannelCode } from '@/lib/channel';
import { getChannel } from '@/lib/channel';
import { buildCookieHeader, type VendureSessionCookies } from '@/lib/session';
import { getSdk } from '@/lib/vendure/generated';

const SHOP_API_URL = process.env.VENDURE_SHOP_API_URL || 'http://localhost:3000/shop-api';

/**
 * One SDK instance per request, scoped to the active channel via the
 * `vendure-token` header. Never cached/module-level — a shared instance would leak
 * one request's channel or session cookie into another's. Returns the typed SDK
 * generated by @graphql-codegen/typescript-graphql-request (see codegen.ts) rather
 * than a raw GraphQLClient, so every call site gets fully-typed query results.
 */
export function getVendureClient(channelCode: ChannelCode, sessionCookies: VendureSessionCookies = {}) {
  const channel = getChannel(channelCode);
  const client = new GraphQLClient(SHOP_API_URL, {
    headers: {
      'vendure-token': channel.vendureToken,
      ...buildCookieHeader(sessionCookies),
    },
  });
  return getSdk(client);
}
